---
controller_projects:
  - name: "Project_Dummy_3"
    description: ""
    organization: "Dummy"
    scm_type: "git"
    scm_url: "https://github.com/automationiberia/dummy-playbooks.git"
    scm_branch: ""
    scm_clean: "False"
    scm_delete_on_update: "False"
    scm_update_on_launch: "False"
    scm_update_cache_timeout: "0"
    allow_override: "False"
    timeout: 0
...
