---
controller_schedules:
  - name: "dummy"
    description: ""
    organization: "Dummy"
    enabled: True
    unified_job_template: "Job_Template_Dummy_1"
    inventory: "Inventory_Dummy_1"
    dtstart: "2023-07-09T22:00:00Z"
    dtend: "2023-07-09T23:30:00Z"
    timezone: "Europe/Berlin"
    rrule: "DTSTART;TZID=Europe/Berlin:20230718T000000 RRULE:FREQ=MINUTELY;INTERVAL=10;COUNT=10"
    extra_data:
      {}
    scm_branch: ""
    job_type: ""
    job_tags: ""
    skip_tags: ""
    limit: ""
    verbosity: 0
...
