---
controller_instance_groups:
  - name: "tower"
    policy_instance_minimum: "0"
    policy_instance_percentage: "0"
    instances:
      - "aap1.bcnconsulting.com"
  - name: "dummy_instance"
    policy_instance_minimum: "0"
    policy_instance_percentage: "0"
    instances:
...
